apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scraper
  namespace: wooglife
spec:
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraper
            image: ghcr.io/woog-life/scraper:{{TAG}}
            envFrom:
            - secretRef:
              name: apikey
            - configMapRef:
              name: lake-uuids
            - configMapRef:
              name: scraper-config
            command:
            - python
            - main.py
          restartPolicy: Never
