apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scraper
  namespace: wooglife
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraper
            image: ghcr.io/woog-life/scraper:{{TAG}}
            command:
            - python
            - main.py
          restartPolicy: Never
